
package packcollictionsosiete;

import java.util.ArrayList;

import java.util.List;
import java.util.Iterator;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
public class CollectionSociete extends javax.swing.JFrame {
   List li ;
    
    public float calculerBenefice(float dep,float rec){
        return rec -dep;
    }
    public float calculerImpot(float ben){
        float imp=0;
        if(ben <= 300000){
            imp = ben *0.15f;
        }else if(ben <= 1000000){
            imp = ben *0.20f;
        }else if(ben <= 100000000){
            imp = ben *0.255f;
        }else {
            imp = ben *0.33f;
        }
        return imp;
    }
    public void nouveau(){
        cmbns.setSelectedIndex(-1);
        txtnoms.setText("");
        txtsa.setText(null);
        txtd.setText(null);
        txtr.setText(null);
        txtb.setText(null);
        txti.setText(null);
        cmbns.requestFocus();
    }
    public void ajouter(List s,Societe soc){
        
        soc.ns=cmbns.getSelectedItem().toString();
        soc.noms=txtnoms.getText();
        soc.sa=txtsa.getText();
        soc.dep=Float.parseFloat(txtd.getText());
        soc.rec=Float.parseFloat(txtr.getText());
        soc.ben=Float.parseFloat(txtb.getText());
        soc.imp=Float.parseFloat(txti.getText());
        s.add(soc);
    }
    public Societe rechercher(List s,String num){
       Societe soc = null;
        Iterator it = s.iterator();
       while(it.hasNext()){
           Societe sc = new Societe();
           sc = (Societe)it.next();
           if(sc.ns.compareTo(num) == 0){
               soc = sc;
               break;
           }
           
       }
       return soc;
    }
    public void lister(List s){
       ((DefaultTableModel)tsociete.getModel()).setRowCount(0);
        Iterator it = s.iterator();
       while(it.hasNext()){
           Societe sc = new Societe();
           sc = (Societe)it.next();
           ((DefaultTableModel)tsociete.getModel()).addRow(new Object[]{sc.ns,sc.noms,sc.sa,sc.ben,sc.imp});

       }
       
    }
    public void modifier(List s, String num){
       Societe soc = new Societe();
       
        Iterator it = s.iterator();
       while(it.hasNext()){
           Societe sc = new Societe();
           sc = (Societe)it.next();
           if(sc.ns.compareTo(num) == 0){
              
               s.remove(sc);
               ajouter(s, soc);
               lister(s);
                JOptionPane.showMessageDialog(this, "Modification est bein enregistre","Modification est bein enregistre",JOptionPane.OK_OPTION);
               break;
           }
       }
    }
    public void supprimer (List s, String num){
        Iterator it = s.iterator();
        while(it.hasNext()){
          Societe sc = new Societe();   
          sc =(Societe)it.next();
          if(sc.ns.compareTo(num)==0){
              int rep = JOptionPane.showConfirmDialog(this, "Etes-vous sur de supprimer cette societe:","Suppression",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
              if(rep == JOptionPane.YES_OPTION){
                    s.remove(sc);
                    lister(s);
                    JOptionPane.showMessageDialog(this, "La suppression est bien effecturée","Suppression",JOptionPane.OK_OPTION);
                    nouveau();
              } 
              break; 
          }
        }
    }
    public CollectionSociete() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmbns = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtnoms = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtsa = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtd = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtr = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtb = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txti = new javax.swing.JTextField();
        bta = new javax.swing.JButton();
        btl = new javax.swing.JButton();
        btr = new javax.swing.JButton();
        btm = new javax.swing.JButton();
        btn = new javax.swing.JButton();
        bts = new javax.swing.JButton();
        btf = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tsociete = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("Calculer des impots sur les sociétés");

        jLabel2.setText("Nom de la sociétés                            :");

        cmbns.setEditable(true);
        cmbns.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbnsItemStateChanged(evt);
            }
        });

        jLabel3.setText("Numiro de la sociétés                            :");

        jLabel4.setText("Secteur d'activité                               :");

        jLabel5.setText("Dépenses annuelles                          :");

        jLabel6.setText("Recettes annuelles                            :");

        txtr.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtrKeyPressed(evt);
            }
        });

        jLabel7.setText("Bénéfice annuelle                              :");

        jLabel8.setText("Imot sur les société                         :");

        txti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtiActionPerformed(evt);
            }
        });

        bta.setText("Ajouter");
        bta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btaActionPerformed(evt);
            }
        });

        btl.setText("Lister");
        btl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btlActionPerformed(evt);
            }
        });

        btr.setText("Rechercher");
        btr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btrActionPerformed(evt);
            }
        });

        btm.setText("Modifier");
        btm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmActionPerformed(evt);
            }
        });

        btn.setText("Nouveau");
        btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActionPerformed(evt);
            }
        });

        bts.setText("Supprimer");
        bts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btsMouseClicked(evt);
            }
        });

        btf.setText("Fermer");

        tsociete.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Numéro société", "Nom société", "Secteurs ", "Bénéfices", "Impôts"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tsociete);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtb, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtr)
                            .addComponent(txti)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(17, 17, 17)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(17, 17, 17)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 24, Short.MAX_VALUE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbns, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtnoms, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                            .addComponent(txtsa)
                            .addComponent(txtd))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(46, 46, 46)
                                            .addComponent(bta, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btr, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btl, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btn, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btm, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(bts, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btf, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbns, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bta, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtnoms, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtsa, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btr, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtd, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btl, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtr, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btm, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtb, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bts, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txti, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btf, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(329, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtiActionPerformed

    private void btrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btrActionPerformed
        Societe sc = new Societe();
        if(cmbns.getSelectedItem().toString().compareTo("")!=0){
          String num = cmbns.getSelectedItem().toString();
           sc = rechercher(li, num);  
           if(sc != null){
               txtnoms.setText(sc.noms);
               txtsa.setText(sc.sa);
               txtd.setText(String.valueOf(sc.dep));
               txtr.setText(String.valueOf(sc.rec));
               txtb.setText(String.valueOf(sc.ben));
               txti.setText(String.valueOf(sc.imp));
           }else{
               JOptionPane.showMessageDialog(this, "Pas de societe avec ce numero","Erreur de recherche",JOptionPane.OK_OPTION);
           }
        }else{
            JOptionPane.showMessageDialog(this, "Entrer le numero de la societe a rechercher","Erreur de saisi",JOptionPane.OK_OPTION);
        }
        
    }//GEN-LAST:event_btrActionPerformed

    private void btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActionPerformed
        nouveau();
    }//GEN-LAST:event_btnActionPerformed

    private void btaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btaActionPerformed
       Societe soc = new Societe();
        if(cmbns.getSelectedItem().toString().compareTo("")!=0){
           ajouter(li, soc); 
            lister(li);
            nouveau();
        }else{
            JOptionPane.showMessageDialog(this, "Entrer le numero de la societe a sauvegarder","Erreur de saisi",JOptionPane.OK_OPTION);
        }
        
    }//GEN-LAST:event_btaActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        li = new ArrayList();
    }//GEN-LAST:event_formWindowOpened

    private void btlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btlActionPerformed
        if(li.size() !=0){
           lister(li); 
        }
    }//GEN-LAST:event_btlActionPerformed

    private void txtrKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtrKeyPressed
        
        if(evt.getKeyChar() == '\n'){
           if(txtd.getText().compareTo("")!=0 && txtr.getText().compareTo("")!=0){
              float d =Float.parseFloat(txtd.getText());
              float r = Float.parseFloat(txtr.getText());
              float ben= calculerBenefice(d,r);
              String impo = String.valueOf(calculerImpot(ben));
              txtb.setText(String.valueOf(ben));
              txti.setText(impo);
           }else{
               JOptionPane.showMessageDialog(this, "Remplir les zone de text depence et recette","Erreur de saisi",JOptionPane.OK_OPTION);
            }
            
        }
    }//GEN-LAST:event_txtrKeyPressed

    private void btmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmActionPerformed
        String num =cmbns.getSelectedItem().toString();
        modifier(li, num);
    }//GEN-LAST:event_btmActionPerformed

    private void cmbnsItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbnsItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbnsItemStateChanged

    private void btsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btsMouseClicked
        String num = cmbns.getSelectedItem().toString();
        supprimer(li, num);
        
    }//GEN-LAST:event_btsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel Listting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CollectionSociete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CollectionSociete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CollectionSociete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CollectionSociete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CollectionSociete().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bta;
    private javax.swing.JButton btf;
    private javax.swing.JButton btl;
    private javax.swing.JButton btm;
    private javax.swing.JButton btn;
    private javax.swing.JButton btr;
    private javax.swing.JButton bts;
    private javax.swing.JComboBox<String> cmbns;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable tsociete;
    private javax.swing.JTextField txtb;
    private javax.swing.JTextField txtd;
    private javax.swing.JTextField txti;
    private javax.swing.JTextField txtnoms;
    private javax.swing.JTextField txtr;
    private javax.swing.JTextField txtsa;
    // End of variables declaration//GEN-END:variables
}
class Societe implements Comparable{
    String ns,noms,sa;
    float dep,rec,ben,imp;
    @Override
    public int compareTo(Object o) {
        return this.ns.compareTo(((Societe)o).ns);
    }
    
}
